# Generated by Django 4.2.2 on 2023-06-22 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelreview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="hotelreview",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="hotelreviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="description",
            field=models.TextField(),
        ),
    ]
