# Generated by Django 4.2.2 on 2023-06-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_hotelreview_options_alter_hotel_description'),
        ('base', '0002_alter_hotelreview_options_hotelreview_author_and_more'),
    ]

    operations = [
    ]
