# Generated by Django 4.2.2 on 2023-06-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hotelrating_author_alter_hotelreview_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomfeature',
            old_name='hotel',
            new_name='room',
        ),
    ]
