# Generated by Django 4.2.2 on 2023-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_hotelreview_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
