# Generated by Django 4.2.2 on 2023-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_category_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
