# Generated by Django 4.2.2 on 2023-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
