# Generated by Django 4.2.2 on 2023-07-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_booking_room_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='base.room'),
        ),
    ]
