# Generated by Django 4.2.2 on 2023-07-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_booking_created_at_alter_booking_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bookingstatuses",
                to="base.bookingstatus",
            ),
            preserve_default=False,
        ),
    ]
