# Generated by Django 4.2.2 on 2023-07-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_bookingstatus_booking_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
